### ISSUE TITLE
ServerName for hosts with domain part

### ISSUE THREAD

**Issue by valihanov** [iakovmarkov/prometheus-vuls-exporter#2]
Currently, ServerName is determined for hosts with the domain part. For example for hostname example.com ServerName would be "com".
I created a pull request with a fix - #1

**Comment by iakovmarkov** [comment]
Hi @valihanov! 
Thanks for the report and the PR. It looks good on the first glance - I'll test it out during the weekend, and if everything works great I'll merge your PR and create a new release.

**Comment by iakovmarkov** [comment]
Hi @valihanov!
Everything looks fine on my home lab.
I've merged your code and released [version 0.1.3](https://github.com/iakovmarkov/prometheus-vuls-exporter/releases/tag/0.1.3).
Thank you for your contribution!
