### ISSUE TITLE
How to install prometheus vuls exporter send metric to grafana

### ISSUE THREAD

**Issue by hasd-daniel** [iakovmarkov/prometheus-vuls-exporter#3]
Hi All
I deployment vuls and grafana below:
Server A (Grafana/Prometheus server) <----> Server B (Vuls server)
I have question: With such architecture. How can I send metric to Prometheus server.

On Vuls server:
$ export REPORTS_DIR=/root/results
$ export VULS_DIR=/root/vulsctl

[root@VULS prometheus-vuls-exporter]# pwd
/root/prometheus-vuls-exporter
[root@VULS prometheus-vuls-exporter]# ./example/run_exporter.sh 
Running exporter with Go
src/metrics/createMetrics.go:6:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
        /usr/local/go/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
        /root/go/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
src/metrics/createMetrics.go:7:2: cannot find package "github.com/prometheus/client_golang/prometheus/promauto" in any of:
        /usr/local/go/src/github.com/prometheus/client_golang/prometheus/promauto (from $GOROOT)
        /root/go/src/github.com/prometheus/client_golang/prometheus/promauto (from $GOPATH)
src/main.go:12:2: cannot find package "github.com/prometheus/client_golang/prometheus/promhttp" in any of:
        /usr/local/go/src/github.com/prometheus/client_golang/prometheus/promhttp (from $GOROOT)
        /root/go/src/github.com/prometheus/client_golang/prometheus/promhttp (from $GOPATH)
src/main.go:13:2: cannot find package "github.com/spf13/pflag" in any of:
        /usr/local/go/src/github.com/spf13/pflag (from $GOROOT)
        /root/go/src/github.com/spf13/pflag (from $GOPATH)
src/main.go:14:2: cannot find package "github.com/spf13/viper" in any of:
        /usr/local/go/src/github.com/spf13/viper (from $GOROOT)
        /root/go/src/github.com/spf13/viper (from $GOPATH)
src/metrics/parseReport.go:9:2: cannot find package "github.com/tidwall/gjson" in any of:
        /usr/local/go/src/github.com/tidwall/gjson (from $GOROOT)
        /root/go/src/github.com/tidwall/gjson (from $GOPATH)
[root@VULS prometheus-vuls-exporter]#  

Hope my question is not too silly

Thank so much

**Comment by iakovmarkov** [comment]
Hi Daniel. 
If you're running examples from source and not the pre-built binary, you need to install Go dependencies. Go to project root folder and run `go get -u ./...`. This will install/update all packages that it finds.
Alternatively, you can replace the `go ./src` (or whatever command I'm using in the example) with `prometheus-vuls-exporter` binary - you can get it on the Releases page.
Hope this helps!

**Comment by hasd-daniel** [comment]
Thank so much @iakovmarkov 

It seems I have adjusted properly. 
```
[root@VULS tmp]# ls /root/results/
2020-08-02T23:00:00+07:00  2020-08-03T23:00:00+07:00 current

[root@VULS tmp]# prometheus-vuls-exporter 
2020/08/04 16:15:48 prometheus-vuls-exporter Warning! HTTP Basic Auth disabled, your vulnerability metrics are readable by anyone!
2020/08/04 16:15:48 prometheus-vuls-exporter Reports folder configured: /root/results
2020/08/04 16:15:48 prometheus-vuls-exporter listening on :8080
```
But when I configured data source to fetch data from Vuls server is defective.I make sure firewall allow port 8080 from grafana
![image](https://user-images.githubusercontent.com/64135248/89277414-01e94480-d66f-11ea-89ce-74f57c45b07f.png)

Do you have ideal for check metric on vuls server? 

Thank you!!!

**Comment by iakovmarkov** [comment]
The exporter doesn't do much by itself - it collects reports from Vuls and exposes metrics over HTTP in Prometheus-friendly format. You need a running Prometheus instance, and you need to configure it to scrape the metrics from this exporter. The Prometheus configuration is really similar to any other exporter like BlackboxExporter or NodeExporter.

On Grafana side, you need to point it to Prometheus instance - that's where the data is stored, not on the Exporter side. Also, `http://10.*.*.*:8080` cannot be a correct URL. If you're running on Grafana and Prometheus on the same host, you can use `http://localhost` there; otherwise you need Prometheus instance hostname/port combo.

**Comment by hasd-daniel** [comment]
@iakovmarkov 
Really thank you for the suggestion. My system was running smoothly.
I was confused about how Prometheus works.
One more thing. In Installation Guide.
Curl-Lo Prometheus-vuls-exporter https://github.com/iakovmarkov/prometheus-vuls-exporter/releases/latest/prometheus-vuls-exporter-linux-386--> Not work
We need change to: 
https://github.com/iakovmarkov/prometheus-vuls-exporter/releases/tag/0.1.3/prometheus-vuls-exporter-linux-386


Thank so much friend

**Comment by iakovmarkov** [comment]
Glad it worked out for you :+1: 
Thanks for letting me know about README, I thought that the `latest` thing worked at some point... I'll update the README.
