### ISSUE TITLE
Makefile outdated

### ISSUE THREAD

**Issue by m0rd4n** [iakovmarkov/prometheus-vuls-exporter#5]
Hey, when I am trying to `make install`, it is displaying
![image](https://github.com/iakovmarkov/prometheus-vuls-exporter/assets/20155020/e0d3e66d-5029-4b9f-bd90-faeb956c1ee8)
Could you update it?

**Comment by iakovmarkov** [comment]
Hi @m0rd4n! I'm no longer actively developing this exporter. If you know how to fix it, I will gladly welcome any merge request from you though:)
